---
openapi: 3.0.1
info:
  version: '1.0'
  title: Avatar Libraries REST API

servers:
  # DEV without authentication
  - url: http://localhost:8088/fhir/rest
    description: DEV environment server - does not require authentication
